name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Set up Python (if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check if .deb files were uploaded
        id: check_files
        run: |
          # 检查是否有新的 .deb 文件
          if ls debs/*.deb 1> /dev/null 2>&1; then
            echo "new_deb_files=true" >> $GITHUB_ENV
          else
            echo "new_deb_files=false" >> $GITHUB_ENV
          fi

      - name: Run generate_packages.sh
        run: |
          chmod +x ./generate_packages.sh
          ./generate_packages.sh
        env:
          PERSONAL_TOKEN: ${{ secrets.PAT }}

      - name: Output Packages files
        run: ls -l Packages*  # 列出所有相关文件以进行调试

      - name: Commit updated Packages
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add Packages Packages.bz2 Packages.gz  # 添加所有相关文件
          git commit -m "Update Packages" || echo "No changes to commit"
          git push https://${{ secrets.PAT }}@github.com/axs66/repo.git HEAD:main

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
